## -*- coding: utf-8 -*-
##' @name plot.stage
##'
##' @title Plotting of stage result
##'
##' @description Plot method function for calculation result of
##'     staging bird variables, with input class of 'stage'.
##'
##' @param x stage result.
##' @param ... other parameters for plot function.
##'
##' @details Input data should be of 'stage' class, generated by
##'     \code{calculate.stage.variables} function. The stage class is
##'     a list, with item names of: day, daycount, population,
##'     immigrate.mean, immigarate.sd, emigrate.mean, emigrate.sd. You
##'     can make a list with the corresponding value and assign it the
##'     class 'stage' to use this \code{plot.stage} function.
##'
##' @seealso [calculate.stage.variables()] for calculation of stage class.
##'
##' @examples
##' data <- data.frame(
##'     day=c(11, 16, 20, 22, 24, 34, 39, 40, 47, 60),
##'     daycount=c(10, 65, 60, 45, 66, 52, 35, 50, 27, 0)
##' )
##'
##' result <- calculate.stage.variables(
##'     day=data$day,
##'     daycount=data$daycount,
##'     population=85,
##'     immigrate.mean=c(10, 20),
##'     emigrate.mean=c(20, 50),
##'     immigrate.sd=c(4, 10),
##'     emigrate.sd=c(10, 30)
##' )
##'
##' plot(result)
##'
##' @importFrom graphics legend lines plot
##' @export
plot.stage <- function(x, ...) {
    plot(
        x=x$day, y=x$daycount,
        type='p', pch=19, col='red',
        xlim=c(min(x$day), max(x$day)),
        ylim=c(0, x$population * 1.05),
        xlab='Day',
        ylab='Bird count',
        main=paste0(
            paste('Population:', x$population),
            '\n',
            paste(
                'Immigration mean:', round(x$immigrate.mean),
                'Immigration sd:', round(x$immigrate.sd, 2),
                sep=', '
            ),
            '\n',
            paste(
                'Emigration mean:', round(x$emigrate.mean),
                'Emigration sd:', round(x$emigrate.sd, 2),
                sep=', '
            )
        ), ...
    )

    lines(
        seq(min(x$day), max(x$day)),
        stage.number(
            seq(min(x$day), max(x$day)),
            population=x$population,
            immigrate.mean = x$immigrate.mean,
            emigrate.mean = x$emigrate.mean,
            immigrate.sd = x$immigrate.sd,
            emigrate.sd = x$emigrate.sd
        ),
        type='l', lty=1, ...
    )

    lines(
        x=seq(min(x$day), max(x$day)),
        y=migrate.number(
            seq(min(x$day), max(x$day)),
            x$population,
            x$immigrate.mean,
            x$immigrate.sd
        ) - migrate.number(
                seq(min(x$day), max(x$day)) - 1,
                x$population,
                x$immigrate.mean,
                x$immigrate.sd
            ),
        lty=2, ...
    )

    lines(
        x=seq(min(x$day), max(x$day)),
        y=migrate.number(
            seq(min(x$day), max(x$day)),
            x$population,
            x$emigrate.mean,
            x$emigrate.sd
        ) - migrate.number(
                seq(min(x$day), max(x$day)) - 1,
                x$population,
                x$emigrate.mean,
                x$emigrate.sd
            ),
        lty=3, ...
    )

    legend(
        'top',
        legend=c('Stage', 'Immigration', 'Emigration'),
        lty=c(1, 2, 3), ncol=3
    )

}
